"""Feedback schemas — T005 v1.0.0.

Types for the closed-loop learning system:
  FeedbackEntry       → one simulation result's signal
  FeedbackAggregate   → batch summary
  TrainingSample      → learning-to-rank input
  BiasFinding         → reviewer-detected bias
"""

from __future__ import annotations

import uuid
from typing import Literal

from pydantic import BaseModel, Field


class BiasFinding(BaseModel):
    """Reviewer-detected bias or quality issue in simulation output."""

    finding_id: str = Field(
        default_factory=lambda: f"bias-{uuid.uuid4().hex[:8]}",
        description="Unique finding identifier",
    )
    severity: Literal["low", "medium", "high", "critical"] = Field(
        default="medium", description="How urgently this bias must be addressed"
    )
    category: Literal[
        "ranking_bias",
        "skill_bias",
        "confidence_bias",
        "overfitting",
        "data_leakage",
        "other",
    ] = Field(description="Bias category for aggregation and tracking")
    description: str = Field(description="Human-readable description of the finding")
    affected_simulation_ids: list[str] = Field(
        default_factory=list, description="Simulation IDs exhibiting this bias"
    )
    correction_signal: float = Field(
        default=0.0,
        ge=-1.0,
        le=1.0,
        description="Direction and magnitude of correction. Positive = boost, negative = suppress.",
    )
    recommendation: str = Field(default="", description="Suggested mitigation action")


class FeedbackEntry(BaseModel):
    """Signal extracted from one simulation + review cycle."""

    simulation_id: str
    strategy_name: str
    outcome: Literal["accepted", "rejected", "timeout"]

    # From simulation metrics
    total_reward: float = Field(ge=0.0, le=1.0)
    offer_probability: float = Field(ge=0.0, le=1.0)
    skill_gap_score: float = Field(ge=0.0, le=1.0)

    # From reviewer
    retrieval_reward: float = Field(default=0.0, description="Reviewer-assigned retrieval quality")
    ranking_penalty: float = Field(default=0.0, ge=0.0, description="Penalty for poor ranking")
    bias_flags: list[str] = Field(default_factory=list)

    # Combined
    combined_signal: float = Field(default=0.0, description="Weighted combination for policy update")

    # Metadata
    timestamp: int = Field(default=0, description="Epoch seconds")


class FeedbackAggregate(BaseModel):
    """Batch summary of N feedback entries."""

    total_entries: int
    avg_reward: float
    avg_offer_probability: float
    avg_retrieval_reward: float
    total_ranking_penalty: float
    bias_incident_count: int = 0
    entries: list[FeedbackEntry] = Field(default_factory=list)


class TrainingSample(BaseModel):
    """Learning-to-rank sample generated by feedback_agent."""

    features: dict = Field(default_factory=dict, description="Feature vector for ranking model")
    label: float = Field(default=0.0, ge=0.0, le=1.0, description="Target relevance score")
    reward: float = Field(default=0.0, description="Associated reward signal")
    sample_id: str = Field(default="", description="Deterministic ID for dedup")
    source: str = Field(default="simulation", description="Origin: simulation | user_feedback | manual")
    trace_id: str = Field(
        default="",
        description="Pipeline execution ID this sample came from — stamped by DataSignalLayer",
    )
