/** Complete mock data for T010 pipeline demo — no backend required */

import type { T010PipelineOutput } from '@/types/t010';

export const MOCK_PIPELINE_OUTPUT: T010PipelineOutput = {
  execution_id: 'demo-exec-001',
  status: 'success',
  errors: [],

  // Stage 1: Parser + Baseline
  user_profile: {
    user_id: 'demo-user',
    career_goals: ['Senior Backend Engineer', 'Staff Engineer', 'Tech Lead'],
    skills: [
      'Python',
      'FastAPI',
      'PostgreSQL',
      'Docker',
      'Kubernetes',
      'Redis',
      'gRPC',
      'Microservices',
    ],
    experience_years: 3,
    education_level: '本科',
    preferred_locations: ['北京', '上海'],
    preferred_industries: ['互联网', '人工智能'],
    salary_expectation: [400, 650],
    raw_text:
      '目标成为高级后端工程师，掌握 Python、FastAPI、PostgreSQL，有3年经验，本科，期望在北京工作',
  },

  career_data: {
    dataset_id: 'demo-ds-001',
    entries: [
      {
        job_title: 'Senior Backend Engineer',
        required_skills: ['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'Kubernetes'],
        optional_skills: ['AWS', 'Terraform', 'GraphQL'],
        growth_path: ['Junior Backend', 'Backend Engineer', 'Senior Backend', 'Staff Engineer'],
        level: '高级',
        salary_range: [400, 650],
        location: '北京',
        industry: '互联网',
        source: 'sample',
      },
      {
        job_title: 'Machine Learning Engineer',
        required_skills: ['Python', 'PyTorch', 'TensorFlow', 'Machine Learning'],
        optional_skills: ['Kubernetes', 'MLOps', 'NLP'],
        growth_path: ['Data Analyst', 'ML Engineer', 'Senior MLE', 'ML Architect'],
        level: '高级',
        salary_range: [500, 800],
        location: '上海',
        industry: '人工智能',
        source: 'sample',
      },
    ],
    total_entries: 2,
    processed_at: new Date().toISOString(),
  },

  baseline_strategy: {
    baseline_id: 'base-001',
    templates: [
      {
        template_id: 'tpl-backend-001',
        domain: '互联网',
        target_role: 'Senior Backend Engineer',
        typical_skills: ['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'Kubernetes'],
        typical_timeline_months: 24,
        typical_milestones: ['掌握核心框架', '独立设计系统', '带领小团队'],
        recommended_strategies: ['skill_first', 'project_driven'],
        risk_factors: ['技术栈过时', '管理经验不足'],
        source: 'industry_baseline',
      },
    ],
    matched_template_id: 'tpl-backend-001',
    match_confidence: 0.92,
    generated_at: new Date().toISOString(),
  },

  off_path_flags: [
    {
      strategy_id: 'strat-002',
      flag_type: 'skill_order_anomaly',
      severity: 'medium',
      description: '建议先掌握 Kubernetes 再学习 Service Mesh，当前顺序可能导致学习曲线过陡',
      deviation_score: 0.35,
      recommendation: '调整学习顺序：Docker → Kubernetes → Istio',
    },
    {
      strategy_id: 'strat-003',
      flag_type: 'timeline_deviation',
      severity: 'low',
      description: '目标时间线（6个月）略短于行业平均（9个月）',
      deviation_score: 0.22,
      recommendation: '延长至8个月，增加项目实战时间',
    },
  ],

  // Stage 2: Retrieval
  job_recommendations: [
    {
      job_id: 'job-001',
      title: 'Senior Backend Engineer',
      company: '阿里云',
      location: '北京',
      level: 'P6+',
      required_skills: ['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'Kubernetes', 'gRPC'],
      optional_skills: ['阿里云产品', 'Service Mesh', 'Prometheus'],
      salary_range: [450, 700],
      match_score: 0.89,
      match_details: { skill_match: 0.92, location_match: 1.0, level_match: 0.85 },
    },
    {
      job_id: 'job-002',
      title: 'Backend Tech Lead',
      company: '字节跳动',
      location: '北京',
      level: '2-2',
      required_skills: ['Go', 'Microservices', 'Redis', 'Kafka', 'Kubernetes'],
      optional_skills: ['Rust', 'eBPF', 'ClickHouse'],
      salary_range: [500, 800],
      match_score: 0.76,
      match_details: { skill_match: 0.72, location_match: 1.0, level_match: 0.82 },
    },
  ],

  strategy_candidates: [
    {
      strategy_id: 'strat-001',
      strategy_name: 'skill_first',
      description: '优先深度掌握核心技术栈，通过技术深度获取晋升机会',
      match_score: 0.91,
      historical_success_rate: 0.78,
      source: 'baseline',
    },
    {
      strategy_id: 'strat-002',
      strategy_name: 'project_driven',
      description: '通过主导关键项目积累影响力，以项目成果推动职级提升',
      match_score: 0.85,
      historical_success_rate: 0.72,
      source: 'baseline',
    },
    {
      strategy_id: 'strat-003',
      strategy_name: 'cloud_certification',
      description: '获取云厂商高级认证，结合认证知识体系构建技术壁垒',
      match_score: 0.72,
      historical_success_rate: 0.65,
      source: 'retrieval',
    },
    {
      strategy_id: 'strat-004',
      strategy_name: 'open_source',
      description: '通过开源贡献建立技术影响力，吸引头部公司注意',
      match_score: 0.68,
      historical_success_rate: 0.58,
      source: 'retrieval',
    },
  ],

  // Stage 3: Reviewer
  strategy_list: [
    {
      strategy: {
        strategy_id: 'strat-001',
        strategy_name: 'skill_first',
        description: '优先深度掌握核心技术栈，通过技术深度获取晋升机会',
        match_score: 0.91,
        historical_success_rate: 0.78,
        source: 'baseline',
      },
      scores: {
        success_rate: 0.88,
        match_degree: 0.91,
        growth_cycle: 0.76,
        skill_adaptability: 0.82,
      },
      overall_score: 0.87,
      rationale: '与用户现有技能栈高度匹配，技术深度路线风险低，成功率最高',
      rank: 1,
      off_path: false,
      off_path_flags: [],
    },
    {
      strategy: {
        strategy_id: 'strat-002',
        strategy_name: 'project_driven',
        description: '通过主导关键项目积累影响力，以项目成果推动职级提升',
        match_score: 0.85,
        historical_success_rate: 0.72,
        source: 'baseline',
      },
      scores: {
        success_rate: 0.79,
        match_degree: 0.85,
        growth_cycle: 0.82,
        skill_adaptability: 0.74,
      },
      overall_score: 0.81,
      rationale: '适合有项目机会的环境，需要等待合适的项目窗口',
      rank: 2,
      off_path: false,
      off_path_flags: [],
    },
    {
      strategy: {
        strategy_id: 'strat-003',
        strategy_name: 'cloud_certification',
        description: '获取云厂商高级认证，结合认证知识体系构建技术壁垒',
        match_score: 0.72,
        historical_success_rate: 0.65,
        source: 'retrieval',
      },
      scores: {
        success_rate: 0.71,
        match_degree: 0.72,
        growth_cycle: 0.68,
        skill_adaptability: 0.79,
      },
      overall_score: 0.72,
      rationale: '认证成本可控，但市场竞争激烈，需配合实际项目经验',
      rank: 3,
      off_path: true,
      off_path_flags: [
        {
          strategy_id: 'strat-003',
          flag_type: 'skill_order_anomaly',
          severity: 'medium',
          description: '认证学习与项目实战时间冲突',
          deviation_score: 0.35,
          recommendation: '将认证学习融入日常工作中',
        },
      ],
    },
    {
      strategy: {
        strategy_id: 'strat-004',
        strategy_name: 'open_source',
        description: '通过开源贡献建立技术影响力，吸引头部公司注意',
        match_score: 0.68,
        historical_success_rate: 0.58,
        source: 'retrieval',
      },
      scores: {
        success_rate: 0.62,
        match_degree: 0.68,
        growth_cycle: 0.55,
        skill_adaptability: 0.85,
      },
      overall_score: 0.66,
      rationale: '长期收益高但见效慢，适合作为辅助策略',
      rank: 4,
      off_path: false,
      off_path_flags: [],
    },
  ],

  diversity_metric: {
    strategy_diversity: 0.78,
    dimension_balance: {
      success_rate: 0.82,
      match_degree: 0.88,
      growth_cycle: 0.71,
      skill_adaptability: 0.8,
    },
    overfitting_risk: 0.32,
    recommendation: '策略多样性良好，建议维持当前探索范围',
  },

  dynamic_weights: {
    iteration: 12,
    weights: {
      success_rate: 0.3,
      match_degree: 0.28,
      growth_cycle: 0.18,
      skill_adaptability: 0.24,
    },
    weight_history: [
      { success_rate: 0.25, match_degree: 0.25, growth_cycle: 0.25, skill_adaptability: 0.25 },
      { success_rate: 0.28, match_degree: 0.26, growth_cycle: 0.22, skill_adaptability: 0.24 },
    ],
    convergence_delta: 0.008,
    learning_rate: 0.05,
  },

  // Stage 4: Architect
  career_plan: {
    plan_id: 'plan-001',
    user_id: 'demo-user',
    generated_at: new Date().toISOString(),
    selected_strategy: {
      strategy: {
        strategy_id: 'strat-001',
        strategy_name: 'skill_first',
        description: '优先深度掌握核心技术栈',
        match_score: 0.91,
        historical_success_rate: 0.78,
        source: 'baseline',
      },
      scores: {
        success_rate: 0.88,
        match_degree: 0.91,
        growth_cycle: 0.76,
        skill_adaptability: 0.82,
      },
      overall_score: 0.87,
      rationale: '与用户现有技能栈高度匹配',
      rank: 1,
    },
    alternative_strategies: [],
    steps: [
      {
        step_number: 1,
        phase: 'preparation',
        title: '深度掌握 Kubernetes 编排',
        description: '系统学习 K8s 核心概念，完成 CKA 认证',
        duration_days: 60,
        skills_required: ['Docker', 'Linux'],
        skills_acquired: ['Kubernetes', 'Helm', 'CKA'],
        milestones: ['通过 CKA 考试', '部署生产级集群'],
      },
      {
        step_number: 2,
        phase: 'preparation',
        title: '构建高并发系统设计能力',
        description: '学习分布式系统原理，完成 2 个高并发项目',
        duration_days: 90,
        skills_required: ['Redis', 'gRPC', 'Microservices'],
        skills_acquired: ['分布式事务', '熔断限流', '链路追踪'],
        milestones: ['设计百万 QPS 系统', '完成压测优化'],
      },
      {
        step_number: 3,
        phase: 'application',
        title: '投递 Senior Backend 岗位',
        description: '优化简历，重点突出 K8s 和分布式系统经验',
        duration_days: 30,
        skills_required: ['简历优化', '面试技巧'],
        skills_acquired: [],
        milestones: ['获得 3 个面试机会'],
      },
      {
        step_number: 4,
        phase: 'interview',
        title: '技术面试与系统设计',
        description: '准备系统设计面试，模拟算法考核',
        duration_days: 21,
        skills_required: ['系统设计', '算法'],
        skills_acquired: ['面试经验'],
        milestones: ['通过 2 轮技术面试'],
      },
      {
        step_number: 5,
        phase: 'negotiation',
        title: '薪资谈判与 Offer 选择',
        description: '基于市场调研进行合理薪资谈判',
        duration_days: 14,
        skills_required: ['谈判技巧'],
        skills_acquired: ['Offer 评估'],
        milestones: ['获得满意 Offer'],
      },
    ],
    total_duration_days: 215,
    estimated_success_rate: 0.87,
    risk_points: ['技术栈快速迭代', '面试竞争激烈'],
    skill_gaps: ['Service Mesh', '云原生可观测性'],
    recommendation: '优先完成 CKA 认证，同步准备系统设计面试',
  },

  visualization_data: {
    skill_nodes: [
      { skill_name: 'Python', level: 'advanced', dependencies: [], estimated_hours: 0 },
      { skill_name: 'FastAPI', level: 'advanced', dependencies: ['Python'], estimated_hours: 40 },
      { skill_name: 'PostgreSQL', level: 'intermediate', dependencies: [], estimated_hours: 60 },
      { skill_name: 'Docker', level: 'intermediate', dependencies: [], estimated_hours: 30 },
      {
        skill_name: 'Kubernetes',
        level: 'intermediate',
        dependencies: ['Docker'],
        estimated_hours: 120,
      },
      { skill_name: 'Redis', level: 'intermediate', dependencies: [], estimated_hours: 40 },
      {
        skill_name: 'gRPC',
        level: 'beginner',
        dependencies: ['Microservices'],
        estimated_hours: 50,
      },
      {
        skill_name: 'Microservices',
        level: 'intermediate',
        dependencies: ['Docker', 'Kubernetes'],
        estimated_hours: 80,
      },
      {
        skill_name: 'Service Mesh',
        level: 'beginner',
        dependencies: ['Kubernetes', 'Microservices'],
        estimated_hours: 100,
      },
      {
        skill_name: 'Prometheus',
        level: 'beginner',
        dependencies: ['Kubernetes'],
        estimated_hours: 40,
      },
    ],
    skill_edges: [
      ['Python', 'FastAPI'],
      ['Docker', 'Kubernetes'],
      ['Kubernetes', 'Microservices'],
      ['Microservices', 'gRPC'],
      ['Kubernetes', 'Service Mesh'],
      ['Kubernetes', 'Prometheus'],
    ],
    timeline_nodes: [
      {
        week: 1,
        label: '开始学习 K8s',
        event_type: 'skill_acquisition',
        details: '完成基础概念学习',
      },
      { week: 4, label: 'CKA 备考', event_type: 'milestone', details: '完成练习题库' },
      { week: 8, label: '通过 CKA', event_type: 'milestone', details: '获得认证证书' },
      { week: 12, label: '高并发项目 1', event_type: 'skill_acquisition', details: '秒杀系统设计' },
      { week: 20, label: '开始投递', event_type: 'application', details: '投递 10 家公司' },
      { week: 24, label: '拿到 Offer', event_type: 'offer', details: '阿里云 P6+' },
    ],
    primary_path: ['Python', 'FastAPI', 'Docker', 'Kubernetes', 'Microservices'],
    alternative_paths: [
      ['Python', 'FastAPI', 'Docker', 'Kubernetes', 'Service Mesh'],
      ['Python', 'FastAPI', 'Docker', 'Kubernetes', 'Prometheus'],
    ],
    strategy_comparison: {
      skill_first: { success_rate: 0.88, growth_cycle: 0.76, skill_adaptability: 0.82 },
      project_driven: { success_rate: 0.79, growth_cycle: 0.82, skill_adaptability: 0.74 },
      cloud_certification: { success_rate: 0.71, growth_cycle: 0.68, skill_adaptability: 0.79 },
      open_source: { success_rate: 0.62, growth_cycle: 0.55, skill_adaptability: 0.85 },
    },
    render_hints: {},
  },

  interactive_nodes: {
    Python: {
      description: '核心编程语言，所有后端技术的基石',
      strategy_note: '已是高级水平，保持更新即可',
      risk_note: '版本迭代快，需关注 Python 3.12+ 特性',
    },
    Kubernetes: {
      description: '云原生编排平台，现代后端工程师必备技能',
      strategy_note: '重点攻坚方向，建议 2 个月内达到生产级水平',
      risk_note: '学习曲线陡峭，需配合实际项目练习',
    },
    'Service Mesh': {
      description: '服务间通信基础设施，进阶云原生技能',
      strategy_note: '当前技能缺口，可在掌握 K8s 后学习',
      risk_note: '企业采用率仍在增长中',
    },
  },

  // Stage 5: Simulation
  simulation_feedback: {
    base_feedback: {
      simulation_id: 'sim-001',
      career_plan_id: 'plan-001',
      total_rounds: 10,
      successful_rounds: 8,
      average_success_rate: 0.78,
      rounds: [
        {
          round_id: 1,
          success: true,
          success_probability: 0.82,
          risk_triggered: [],
          skill_gaps_exposed: [],
          steps_to_outcome: 5,
          notes: '标准路径',
        },
        {
          round_id: 2,
          success: true,
          success_probability: 0.85,
          risk_triggered: [],
          skill_gaps_exposed: [],
          steps_to_outcome: 5,
          notes: '技能匹配度高',
        },
        {
          round_id: 3,
          success: false,
          success_probability: 0.42,
          risk_triggered: ['面试竞争激烈'],
          skill_gaps_exposed: ['系统设计深度不足'],
          steps_to_outcome: 3,
          notes: '面试准备不充分',
        },
        {
          round_id: 4,
          success: true,
          success_probability: 0.79,
          risk_triggered: [],
          skill_gaps_exposed: [],
          steps_to_outcome: 5,
          notes: '正常推进',
        },
        {
          round_id: 5,
          success: true,
          success_probability: 0.88,
          risk_triggered: [],
          skill_gaps_exposed: [],
          steps_to_outcome: 4,
          notes: '项目经验丰富',
        },
        {
          round_id: 6,
          success: false,
          success_probability: 0.38,
          risk_triggered: ['技术栈过时'],
          skill_gaps_exposed: ['Service Mesh'],
          steps_to_outcome: 2,
          notes: '技术栈评估偏差',
        },
        {
          round_id: 7,
          success: true,
          success_probability: 0.81,
          risk_triggered: [],
          skill_gaps_exposed: [],
          steps_to_outcome: 5,
          notes: '稳步前进',
        },
        {
          round_id: 8,
          success: true,
          success_probability: 0.76,
          risk_triggered: [],
          skill_gaps_exposed: [],
          steps_to_outcome: 6,
          notes: '时间线略长',
        },
        {
          round_id: 9,
          success: true,
          success_probability: 0.83,
          risk_triggered: [],
          skill_gaps_exposed: [],
          steps_to_outcome: 5,
          notes: '综合表现良好',
        },
        {
          round_id: 10,
          success: true,
          success_probability: 0.8,
          risk_triggered: [],
          skill_gaps_exposed: [],
          steps_to_outcome: 5,
          notes: '最终验证通过',
        },
      ],
      aggregated_risks: {
        面试竞争激烈: 0.35,
        技术栈过时: 0.28,
        时间线偏差: 0.22,
        管理经验不足: 0.18,
        薪资谈判失败: 0.12,
      },
      aggregated_skill_gaps: {
        'Service Mesh': 0.45,
        系统设计深度: 0.38,
        云原生可观测性: 0.32,
        性能调优: 0.25,
      },
      recommendation: '加强系统设计面试准备，补充 Service Mesh 知识',
    },
    weight_updates_applied: 3,
    updated_weights: {
      iteration: 15,
      weights: {
        success_rate: 0.32,
        match_degree: 0.27,
        growth_cycle: 0.17,
        skill_adaptability: 0.24,
      },
      weight_history: [],
      convergence_delta: 0.005,
      learning_rate: 0.05,
    },
    off_path_strategies_detected: ['strat-003'],
    rl_iteration: 15,
    rl_converged: true,
  },

  refined_strategy_list: [
    {
      strategy: {
        strategy_id: 'strat-001',
        strategy_name: 'skill_first',
        description: '优先深度掌握核心技术栈，通过技术深度获取晋升机会（已优化）',
        match_score: 0.93,
        historical_success_rate: 0.78,
        source: 'refined',
      },
      scores: {
        success_rate: 0.9,
        match_degree: 0.93,
        growth_cycle: 0.78,
        skill_adaptability: 0.84,
      },
      overall_score: 0.89,
      rationale: '经模拟验证后微调权重，成功率提升 2%',
      rank: 1,
      off_path: false,
      off_path_flags: [],
    },
  ],

  // Stage 6: Frontend
  frontend_data: {
    summary: {
      headline: '推荐策略：技术深度优先路线',
      user_skills: ['Python', 'FastAPI', 'PostgreSQL', 'Docker'],
      career_goals: ['Senior Backend Engineer', 'Staff Engineer'],
      total_jobs_matched: 2,
      top_strategy_score: 0.89,
      simulation_success_rate: 0.78,
      simulation_rounds: 10,
    },
    career_path_graph: {} as unknown,
    strategy_comparison: {
      strategies: [
        {
          name: 'skill_first',
          overall: 0.89,
          success_rate: 0.9,
          match_degree: 0.93,
          growth_cycle: 0.78,
          skill_adaptability: 0.84,
          rank: 1,
        },
        {
          name: 'project_driven',
          overall: 0.81,
          success_rate: 0.79,
          match_degree: 0.85,
          growth_cycle: 0.82,
          skill_adaptability: 0.74,
          rank: 2,
        },
        {
          name: 'cloud_certification',
          overall: 0.72,
          success_rate: 0.71,
          match_degree: 0.72,
          growth_cycle: 0.68,
          skill_adaptability: 0.79,
          rank: 3,
        },
        {
          name: 'open_source',
          overall: 0.66,
          success_rate: 0.62,
          match_degree: 0.68,
          growth_cycle: 0.55,
          skill_adaptability: 0.85,
          rank: 4,
        },
      ],
      dimensions: ['success_rate', 'match_degree', 'growth_cycle', 'skill_adaptability'],
    } as unknown,
    action_timeline: [
      {
        step_number: 1,
        phase: 'preparation',
        title: '深度掌握 Kubernetes',
        description: '系统学习 K8s，完成 CKA 认证',
        start_day: 0,
        end_day: 60,
        duration_days: 60,
        milestones: ['通过 CKA'],
      },
      {
        step_number: 2,
        phase: 'preparation',
        title: '高并发系统设计',
        description: '学习分布式原理，完成实战项目',
        start_day: 60,
        end_day: 150,
        duration_days: 90,
        milestones: ['百万 QPS 系统设计'],
      },
      {
        step_number: 3,
        phase: 'application',
        title: '投递简历',
        description: '优化简历，投递目标岗位',
        start_day: 150,
        end_day: 180,
        duration_days: 30,
        milestones: ['获得面试机会'],
      },
      {
        step_number: 4,
        phase: 'interview',
        title: '面试准备',
        description: '系统设计与算法面试',
        start_day: 180,
        end_day: 201,
        duration_days: 21,
        milestones: ['通过技术面试'],
      },
      {
        step_number: 5,
        phase: 'negotiation',
        title: 'Offer 谈判',
        description: '薪资谈判与选择',
        start_day: 201,
        end_day: 215,
        duration_days: 14,
        milestones: ['获得满意 Offer'],
      },
    ] as unknown,
    simulation_chart: {
      rounds: [
        { round: 1, probability: 0.82, success: true },
        { round: 2, probability: 0.85, success: true },
        { round: 3, probability: 0.42, success: false },
        { round: 4, probability: 0.79, success: true },
        { round: 5, probability: 0.88, success: true },
        { round: 6, probability: 0.38, success: false },
        { round: 7, probability: 0.81, success: true },
        { round: 8, probability: 0.76, success: true },
        { round: 9, probability: 0.83, success: true },
        { round: 10, probability: 0.8, success: true },
      ],
      average: 0.78,
      successful: 8,
      total: 10,
      top_risks: { 面试竞争激烈: 0.35, 技术栈过时: 0.28, 时间线偏差: 0.22 },
      top_gaps: { 'Service Mesh': 0.45, 系统设计深度: 0.38, 云原生可观测性: 0.32 },
    } as unknown,
    recommendations: [
      {
        priority: 1,
        type: 'skill',
        title: '优先完成 CKA 认证',
        description: 'Kubernetes 是当前最重要的技能缺口',
      },
      {
        priority: 2,
        type: 'interview',
        title: '加强系统设计准备',
        description: '模拟面试中 20% 失败源于系统设计深度不足',
      },
      {
        priority: 3,
        type: 'timeline',
        title: '预留缓冲时间',
        description: '建议将时间线从 6 个月延长至 8 个月',
      },
    ] as unknown,
  },

  privacy_mask: {
    mask_personal_info: true,
    mask_company_names: false,
    mask_salary: false,
    anonymization_level: 'basic',
    masked_fields: ['user_id'],
  },

  feedback_loop: {
    state_id: 'fb-001',
    retrieval_reviewer_iterations: 3,
    reviewer_weight_updates: 12,
    simulation_feedback_applied: true,
    simulation_rounds_run: 10,
    user_feedback_received: false,
    user_strategy_adopted: null,
    user_behavior_preferences: {},
    pipeline_converged: true,
    convergence_reason: '权重收敛 delta < 0.01',
  },

  upgrade_interfaces: {
    parser: {
      agent: 'ParserAgent',
      core_capability: '自然语言解析',
      upgrade_hooks: ['multi_language', 'industry_taxonomy'],
      upgrade_notes: '支持更多行业和职位分类',
      version: '1.0',
    },
    retrieval: {
      agent: 'RetrievalAgent',
      core_capability: '职位与策略检索',
      upgrade_hooks: ['real_time_jobs', 'company_insights'],
      upgrade_notes: '接入实时招聘数据',
      version: '1.0',
    },
  },

  elapsed_ms: 2847,
  generated_at: new Date().toISOString(),
  version: 't010-v1.2.0',
};
